# General communication and addressing parameters
node:
  trajectory-node-name: trajectory                         # Name of the trajectory extraction node
  transform-node-name: transform_batch_server              # Name of the transform service node
  visualization-node-name: visualization

  perception-viz-topic: /perception_viz_topic
  object-bbox-topic: /object_bounding_box
  image-topic: /forwardCamera/image_raw                    # Front camera topic                  :                       [Image]                              ⟶ trafficsigns, circulation
  camerainfo-topic: /forwardCamera/camera_info             # Front camera info topic             :                       [CameraInfo]                         ⟶ trafficsigns, circulation
  velocity-topic: /ZOE2UTBM/car/velocity                   # Vehicle velocity data topic         :                       [TwistStamped]                       ⟶ transformtrack
  pointcloud-topic: /lidar                                 # Lidar pointcloud topic              :                       [PointCloud2]                        ⟶ trafficsigns
  trajectory-topic: /navigation/trajectory                 # Trajectory topic                    : circulation        ⟶ [circulation.msg.Trajectory]         ⟶ control 
  direction-topic: /navigation/direction                   # Direction for the next intersection : direction, control ⟶ [Uint8]                              ⟶ circulation
  object-info-topic: /perception/objects-info             # Traffic signs topic                 : trafficsigns       ⟶ [trafficsigns.msg.TrafficSignStatus] ⟶ circulation, control
  speed-topic: /ZOE2UTBM/control/speed                     # Vehicle speed control topic         : control            ⟶ [Float32]
  speed-cap-topic: /ZOE2UTBM/control/max_speed             # Vehicle speed cap topic             : control            ⟶ [Float32]
  steering-angle-topic: /ZOE2UTBM/control/steering_angle   # Vehicle steering topic              : control            ⟶ [Float32]
  lines-viz-topic: /navigation/viz/lines                   # Line detection visualization        : circulation        ⟶ [Image]                              ⟶ rviz
  trajectory-viz-topic: /navigation/viz/trajectory         # Trajectory visualization            : circulation        ⟶ [Image]                              ⟶ rviz
  trafficsigns-viz-topic: /navigation/viz/trafficsigns     # Line detection visualization        : trafficsigns       ⟶ [Image]                              ⟶ rviz
  image-topic-width: 1028
  image-topic-height: 771

  transform-service-name: /circulation/TransformBatch      # Transform service address
  drop-service-name: /circulation/DropVelocity             # Transform service data drop address. To be used ONLY by circulation

  world-frame: map                                         # Fixed frame of reference
  car-frame: base_link                                    # Reference frame for the vehicle. (X, Y) is the ground / road plane, Z points upward, the origin in right underneath the vehicle
  forward-camera-frame: camera_forward_optical_frame

  visualize: true                                          # Enable visualizations
  time-discrepancy: false                                  # Correct the timestamp discrepancies in the simulator versions < 27/12/2022 messages

  road-network-path: src/road_network.json  

model:
  detection-model-class-names-path: src/models/yolov4-tiny/classes.names
  yolov4-weights-path: src/models/yolov4-tiny/yolov4-tiny.weights
  yolov4-config-path: src/models/yolov4-tiny/yolov4-tiny.cfg
  yolov5n-onnx-model-path: src/models/yolov5n/YOLOv5n.onnx
  yolov5n6-onnx-model-path: src/models/yolov5n/YOLOv5n6.onnx



# # Transform service parameters
# transform:
#   sim-interval: 0.005                                      # Integration interval in the transform service, in seconds. Lower ⟶ more precision, less performance

# # Bird-eye view parameters
# birdeye:
#   x-range: 15                                              # The bird-eye view encompasses [-x-range, +x-range] meters on the X axis (left-right)
#   y-range: 21.8                                            # The bird-eye view encompasses [+roi-y  , +y-range] meters on the Y axis (forward)
#   roi-y: 3                                                 # Closest distance forward for meaningful data from the camera
#   birdeye-size: 500                                        # Height of the bird-eye view in pixels. The width is deduced such that the y-range to x-range proportions are kept

# Visualization parameters
visualization:
  circulation-lines-id: 0
  circulation-trajectory-id: 1
  trafficsigns-id: 2