node:
  image-topic: /forwardCamera/image_raw
  camerainfo-topic: /forwardCamera/camera_info
  velocity-topic: /ZOE2UTBM/car/velocity
  trajectory-topic: /navigation/trajectory
  direction-topic: /navigation/direction
  pointcloud-topic: /lidar